// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/10/2026, 8:34:15 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/plugins/**/*.{js,ts,mjs}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/composables/**/*.{js,ts,mjs}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/utils/**/*.{js,ts,mjs}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/alejandrolissanchez/Documents/Development/Apps/Simuladores/landing-rrivera/rrivera/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;